all:
  children:
    webservers:
      hosts:
        ovid:
          ansible_host: 127.0.0.1
          ansible_port: 2201
    dbservers:
      hosts:
        vergil:
          ansible_host: 127.0.0.1
          ansible_port: 2202
